#!/bin/sh

# update-motd
#
# Copyright (C) 2013 Kano Computing Ltd. 
# License:   http://www.gnu.org/licenses/gpl-2.0.txt GNU General Public License v2
#
# Required-Start:    hostname $local_fs $remote_fs
# Default-Start:     1 2 3 4 5
# Short-Description: Create dynamic part of /etc/motd
# Description:       /etc/motd is user-editable and static.  This script
#                    creates the initial dynamic part, by default the
#                    output of uname, and stores it in /var/run/motd.dynamic.
#                    Both parts are output by pam_motd.

PATH=/sbin:/usr/sbin:/bin:/usr/bin
. /lib/init/vars.sh

do_start () {
	# Update motd
    kano-motd random >/var/run/motd.dynamic
}

do_status () {
	if [ -f /var/run/motd.dynamic ] ; then
		return 0
	else
		return 4
	fi
}

case "$1" in
  start|"")
	do_start
	;;
  restart|reload|force-reload)
	echo "Error: argument '$1' not supported" >&2
	exit 3
	;;
  stop)
	# No-op
	;;
  status)
	do_status
	exit $?
	;;
  *)
	echo "Usage: motd [start|stop|status]" >&2
	exit 3
	;;
esac
